blank_issues_enabled: false
contact_links:
  - name: 💡 Feature Requests
    url: .github/ISSUE_TEMPLATE/feature_request.yml
    about: Suggest new features or improvements
  - name: 🎨 Design Proposals
    url: .github/ISSUE_TEMPLATE/design_proposal.yml
    about: Share UI/UX improvements or visual ideas