blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and Help
    url: https://github.com/your-repo/discussions
    about: Please use the discussions tab for questions and help
  - name: 💡 Feature Requests
    url: https://github.com/your-repo/discussions/new?category=ideas
    about: Suggest new features or improvements in our discussions
  - name: 🎨 Design Proposals
    url: https://github.com/your-repo/discussions/new?category=design
    about: Share UI/UX improvements, visual assets, or animation ideas in our design discussions