name: 💡 Feature Request
description: Suggest a new feature for Smack Mouch
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What would you like to see added?
      placeholder: Describe the feature and its benefits...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature be used?
      placeholder: Explain when and how players would use this feature...
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: Final checks
      options:
        - label: This feature fits the game's style and theme
          required: true 